version: "3"
services:
    postgres-server:
        image: "postgres:latest"
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    node-app:
        image: radhab11/simpleblog
        #build:
            #context:.
            #dockerfile: dockerfile.prod
        volumes:
            - /app/node_modules
            - ./:/app
        environment:
            - POSTGRES_HOST=postgres-server
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
        ports:
            - "3000:3000"